// coachingData.js
// Pre-computed coaching knowledge — session type progressions and description templates.
// Generated by scripts/generateCoachingData.js (Claude) and committed so the
// production server never makes a runtime API call to generate plans.
//
// To regenerate:   node scripts/generateCoachingData.js

// ── Session type sequences ─────────────────────────────────────────────────────
//
// For each named phase and non-long session slot count (1–5), specifies
// which session types to use. The array is ordered by scheduling priority:
// the hardest quality session goes first (placed furthest from the long run
// when the algorithm distributes sessions across the week).
//
// Phases: base → build → peak → taper (recovery weeks use the 'recovery' row)
//
const PHASE_TYPES = {
  base: {
    1: ['strides'],
    2: ['easy', 'strides'],
    3: ['easy', 'strides', 'easy'],
    4: ['easy', 'strides', 'easy', 'easy'],
    5: ['easy', 'easy', 'strides', 'easy', 'easy'],
  },
  build: {
    1: ['tempo'],
    2: ['tempo', 'easy'],
    3: ['easy', 'tempo', 'easy'],
    4: ['easy', 'tempo', 'easy', 'easy'],
    5: ['easy', 'easy', 'tempo', 'easy', 'easy'],
  },
  peak: {
    1: ['intervals'],
    2: ['intervals', 'tempo'],
    3: ['easy', 'intervals', 'tempo'],
    4: ['easy', 'intervals', 'easy', 'tempo'],
    5: ['easy', 'easy', 'intervals', 'easy', 'tempo'],
  },
  taper: {
    1: ['easy'],
    2: ['easy', 'tempo'],
    3: ['easy', 'easy', 'tempo'],
    4: ['easy', 'easy', 'easy', 'tempo'],
    5: ['easy', 'easy', 'easy', 'easy', 'tempo'],
  },
  recovery: {
    1: ['easy'],
    2: ['easy', 'easy'],
    3: ['easy', 'easy', 'easy'],
    4: ['easy', 'easy', 'easy', 'easy'],
    5: ['easy', 'easy', 'easy', 'easy', 'easy'],
  },
};

// Goal-specific overrides applied on top of PHASE_TYPES.
// Keys are session types that get replaced; values are the replacement.
// Only differences from the default (half-marathon) are listed.
const GOAL_TYPE_OVERRIDES = {
  marathon: {
    // Marathon training prioritises prolonged aerobic work over VO2max stress.
    // Replace peak intervals with tempo to keep volume quality-appropriate.
    intervals: 'tempo',
  },
  general: {
    // General fitness: drop structured quality, keep it aerobic and enjoyable.
    intervals: 'strides',
    tempo:     'easy',
  },
};

// ── Long run description variants by phase ────────────────────────────────────
//
// The long run changes character across phases. These strings are appended to
// the base long run description by the plan builder.
//
const LONG_RUN_PHASE_NOTES = {
  base:  'Run the entire distance at easy/long pace. Time on feet is the training stimulus — pace is secondary. If you need to walk, walk.',
  build: 'Run the first two thirds at easy/long pace. Gradually pick up to goal race pace for the final third. Do not start too fast — patience in the first half is the whole point.',
  peak:  'First half at easy/long pace. Second half at goal race pace. This is the most race-specific session in your plan — nail the pacing. Practice your race-day fuelling strategy exactly.',
  taper: 'A reduced-distance long run to maintain range of motion and feel for distance without adding fatigue. Keep the full run at easy pace. The fitness is already built.',
};

// ── Session description templates ─────────────────────────────────────────────
//
// Keyed by session type. The algorithm fills in rep counts, distances, and
// pace values — these templates provide the coaching rationale and structure.
// Descriptions intentionally omit specific pace numbers (those come from
// target_pace_min_km and are shown separately in the UI).
//
const SESSION_TEMPLATES = {
  easy: {
    base:     'Comfortable aerobic pace — you should be able to speak in full sentences throughout. This is the most important discipline in running: the ability to run slowly. The aerobic base you build here underpins every hard session ahead.',
    build:    'Genuine recovery pace. Your legs should feel better at the end than the start. Resist the urge to push — this run supports adaptation from your quality sessions, it is not fitness work in itself.',
    peak:     'Active recovery between hard sessions. Stay truly aerobic and relaxed. Your body is absorbing the stimulus from the quality work; do not compromise that by pushing the easy runs.',
    taper:    'Short shakeout. Keep the legs moving and the mind calm. You are not building fitness here — you are staying sharp while your body consolidates everything it has absorbed.',
    recovery: 'Full recovery run. Easy pace, easy effort, easy mind. This week is purposefully lighter to allow adaptation. Trust the process and resist adding extra distance or intensity.',
  },

  strides: {
    base:  'Run easy for the main distance, then add 4–6 × 100m strides. For each stride: accelerate smoothly over the first 30m to a controlled fast effort, hold it for 40m, then decelerate the final 30m. Walk back fully before the next. Strides develop neuromuscular efficiency and running economy without accumulating meaningful fatigue.',
    build: 'Finish your easy run with 4 × 100m strides at a quick, controlled effort. Focus on tall posture, quick turnover, and relaxed shoulders. These keep your fast-twitch fibres engaged during high-volume weeks.',
  },

  tempo: {
    build:    'Warm up 10–15 min easy. Run the tempo block at threshold pace — comfortably hard, sustainable for around 60 minutes at maximum. You should be able to say three or four words but not a sentence. Cool down 10–15 min easy. Threshold running raises your lactate ceiling and is the cornerstone of race-pace fitness.',
    peak:     'Warm up 10 min easy. This week, the tempo is broken into cruise intervals: 3 × 8 min at threshold pace with 90 sec easy jog recovery. Cool down easy. Shorter blocks with brief recovery deliver the same threshold stimulus with less accumulated fatigue — ideal in a high-intensity week.',
    taper:    'Warm up 10 min easy. Run 2 × 6 min at threshold pace with 2 min jog recovery. Cool down easy. The short duration is intentional — just enough to stay sharp without adding pre-race fatigue. You should finish feeling like you had more in the tank.',
    recovery: 'Easy run only today. On a recovery week, quality sessions are replaced by aerobic work to allow full adaptation. You will return to threshold work next week.',
  },

  intervals: {
    build: 'Warm up 10–15 min easy. Intervals at interval pace (approximately 10K race effort). Stay controlled — hit each rep consistently rather than going out hard and fading. The recovery between reps is part of the session; take it fully. Cool down 10 min easy. These efforts develop your aerobic ceiling and race-pace tolerance.',
    peak:  'Warm up 10–15 min easy. At peak fitness, these interval sessions sharpen your ability to sustain race pace and beyond. Focus on even splits: the last rep should be no slower than the first. Standing or walking recovery between reps — do not jog. Cool down 10 min easy.',
  },

  progression: {
    build: 'Start at easy pace and build gradually every 10–15 minutes, finishing the final segment at tempo effort. No sudden jumps — think of it as a continuous smooth acceleration. Teaches your body to run strong when fatigued, which is exactly what late-race miles demand.',
    peak:  'Begin easy and build steadily over the full run, finishing the last 20% at goal race pace. The effort should feel controlled right up to the end — if you are sprinting the final kilometre, you started the build too late.',
  },

  fartlek: {
    base:  'Warm up 10 min easy. Run a series of unstructured surges: pick a landmark ahead and run hard to it, then recover easy until you feel ready to go again. The hard efforts should be roughly 1 min; recovery 90 sec to 2 min. Cool down 5–10 min easy. Fartlek is play — use it to learn how it feels to shift gears without the pressure of hitting exact splits.',
    build: 'Warm up 10 min easy. Run structured surges: 6–8 × 1 min at a hard but controlled effort (not a sprint) with 90 sec easy jog recovery. Cool down easy. This introduces faster running into your programme while keeping the total volume manageable.',
  },

  hills: {
    build: 'Find a moderate hill (5–8% grade, 60–90 sec to climb). Warm up 10 min on flat. Drive hard uphill — short, powerful strides, high arm drive, keep your chest tall. Jog back down as full recovery. Cool down 10 min easy. Hill reps build strength and power without the injury risk of flat speed work.',
    peak:  'Warm up 10 min easy. Hill reps at maximum controlled effort — think 5K race intensity but shorter. Each rep develops your leg drive and power. Jog the full descent as recovery. Cool down easy.',
  },

  shakeout: {
    race: 'Easy 20–30 min jog — nothing more. The goal is to flush any stiffness and remind your legs they know how to run. Finish with 4 × 100m strides at race pace effort to prime your neuromuscular system. Completely rest tomorrow. Your fitness is locked in — this run changes nothing about your fitness but everything about how you feel on race morning.',
  },

  race: {
    race: 'Warm up 10–15 min easy with a few light accelerations up to race pace. Line up calm. Start the first half 5–10 seconds per km slower than goal pace — it will feel too easy, which means it is correct. Build through the middle kilometres. If you have executed the first half well, you will have genuine energy for the final push. Negative split: come home faster than you went out.',
  },
};

// ── Phase boundary calculator ─────────────────────────────────────────────────
//
// Converts a 0–1 buildPhase fraction into a named phase string.
// Used by plan.js to look up the correct coaching data row.
//
function buildPhaseToName(buildPhase, isTaper) {
  if (isTaper)          return 'taper';
  if (buildPhase < 0.3) return 'base';
  if (buildPhase < 0.65) return 'build';
  return 'peak';
}

// ── Session type resolver ─────────────────────────────────────────────────────
//
// Returns the array of session types for non-long slots in a given week.
// Applies goal-specific overrides to the base phase sequence.
//
function resolveSessionTypes(nonLongCount, phaseName, goal, isRecovery) {
  const effectivePhase = isRecovery ? 'recovery' : phaseName;
  const slots = clamp(nonLongCount, 1, 5);
  const base  = (PHASE_TYPES[effectivePhase] || PHASE_TYPES.build)[slots] || ['easy'];

  const overrides = GOAL_TYPE_OVERRIDES[goal] || {};
  return base.map(t => overrides[t] || t);
}

// ── Description lookup ────────────────────────────────────────────────────────
//
// Returns the coaching description for a session type in a given phase.
// Falls back gracefully: same type different phase → default text.
//
function getSessionDescription(type, phaseName) {
  const byPhase = SESSION_TEMPLATES[type];
  if (!byPhase) return null;
  return byPhase[phaseName] || byPhase.build || byPhase.base || Object.values(byPhase)[0] || null;
}

function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

module.exports = {
  PHASE_TYPES,
  GOAL_TYPE_OVERRIDES,
  LONG_RUN_PHASE_NOTES,
  SESSION_TEMPLATES,
  buildPhaseToName,
  resolveSessionTypes,
  getSessionDescription,
};
