#!/usr/bin/env node
// scripts/generateCoachingData.js
//
// One-time script: calls Claude to regenerate backend/coachingData.js with
// richer, more expert coaching content. Run this offline whenever you want to
// improve the coaching knowledge baked into the plan builder.
//
// Usage:
//   ANTHROPIC_API_KEY=sk-ant-... node scripts/generateCoachingData.js
//
// The script writes a new coachingData.js to the backend root.
// Review the diff, run the app, then commit if satisfied.

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });

const Anthropic = require('@anthropic-ai/sdk');
const fs        = require('fs');
const path      = require('path');

const OUTPUT_PATH = path.join(__dirname, '../coachingData.js');

// ── Prompt ────────────────────────────────────────────────────────────────────

const SYSTEM = `You are an expert running coach and JavaScript developer. You output only valid JavaScript module code — no markdown, no explanation, no preamble. The code you produce will be written directly to a .js file and required by a Node.js backend.`;

const USER = `Generate a complete JavaScript module called coachingData.js for a running plan application.

The module must export these items exactly:

1. PHASE_TYPES — Object keyed by phase name ("base", "build", "peak", "taper", "recovery").
   Each phase maps to an object keyed by non-long session slot count (1–5).
   Each value is an array of session type strings ordered by scheduling priority
   (hardest quality session first, to be placed furthest from the long run).
   Valid session types: "easy", "strides", "tempo", "intervals", "progression", "fartlek", "hills".

2. GOAL_TYPE_OVERRIDES — Object keyed by goal ("marathon", "general", "5k", "10k").
   Each value is an object mapping session type strings to replacement strings.
   Only list goals that genuinely differ from the half-marathon default.

3. LONG_RUN_PHASE_NOTES — Object keyed by phase ("base", "build", "peak", "taper").
   Each value is a coaching string explaining how the long run changes character
   in that phase (e.g. easy throughout in base, race-pace finish in peak).
   Make these detailed, practical, and motivating.

4. SESSION_TEMPLATES — Object keyed by session type, then by phase name.
   Each leaf is a coaching description string (2–4 sentences).
   Apply Jack Daniels VDOT methodology, 80/20 polarised training, and
   periodisation principles. Descriptions must:
   - NOT include specific pace numbers (those come from the algorithm)
   - Include the physiological rationale (what adaptation this produces)
   - Include a brief structural cue (warm-up, main set, cool-down where relevant)
   - Be practically actionable for a self-coached runner
   Cover these type × phase combinations at minimum:
   easy × {base, build, peak, taper, recovery}
   strides × {base, build}
   tempo × {build, peak, taper}
   intervals × {build, peak}
   progression × {build, peak}
   fartlek × {base, build}
   hills × {build, peak}
   shakeout × {race}
   race × {race}

5. buildPhaseToName(buildPhase, isTaper) — function: 0–1 float + bool → "base"|"build"|"peak"|"taper"

6. resolveSessionTypes(nonLongCount, phaseName, goal, isRecovery) — function:
   Looks up PHASE_TYPES[effectivePhase][clamp(nonLongCount,1,5)], applies
   GOAL_TYPE_OVERRIDES[goal] substitutions, returns array of type strings.

7. getSessionDescription(type, phaseName) — function:
   Returns SESSION_TEMPLATES[type][phaseName] with graceful fallback.

8. A private clamp(v, lo, hi) helper.

End with:
module.exports = {
  PHASE_TYPES, GOAL_TYPE_OVERRIDES, LONG_RUN_PHASE_NOTES, SESSION_TEMPLATES,
  buildPhaseToName, resolveSessionTypes, getSessionDescription,
};

Output ONLY the JavaScript module. Start with the comment line:
// coachingData.js — generated by scripts/generateCoachingData.js`;

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('ANTHROPIC_API_KEY not set. Export it or add to backend/.env');
    process.exit(1);
  }

  console.log('Calling Claude to generate coaching data...');
  const client = new Anthropic();

  const response = await client.messages.create({
    model:      'claude-sonnet-4-6',
    max_tokens: 8000,
    system: [{ type: 'text', text: SYSTEM, cache_control: { type: 'ephemeral' } }],
    messages: [{ role: 'user', content: USER }],
  });

  const code = response.content[0]?.text?.trim();
  if (!code) { console.error('Empty response from Claude'); process.exit(1); }

  // Quick sanity check — must look like a JS module
  if (!code.includes('module.exports') || !code.includes('PHASE_TYPES')) {
    console.error('Response does not look like a valid JS module:\n', code.slice(0, 300));
    process.exit(1);
  }

  fs.writeFileSync(OUTPUT_PATH, code, 'utf8');
  console.log(`Written to ${OUTPUT_PATH}`);
  console.log(`Input tokens: ${response.usage?.input_tokens}, Output: ${response.usage?.output_tokens}`);
  console.log('Review the diff with: git diff backend/coachingData.js');
}

main().catch(err => { console.error(err); process.exit(1); });
